### ISSUE TITLE
Css

### ISSUE THREAD

**Issue by kidflex1440** [kidflex1440/P-gina-mia#2]
```css
body{height: 100vh;
		display: flex;
		justify-content: center;
		align-items: center;
}

form{display: flex;
flex-direction: column;
		width: 300px;
		font-family: 'segoe UI', Tahoma, Geneva;
}

form div{display: flex;
		flex-direction: column;
		position: relative;
}

form div input{color: #706c6c;
		background: none;
		border: solid 1px rgba(0,0,0,.1);
		border-radius: 4px;
		padding: 14px;
		font-family: 'segoe UI', Tahoma, Geneva;
		font-size: 16px;
}

input:focus{border: solid 2px rgb(26,115,232);
		outline: none;
}

form div label{font-size: 18px;
		position: absolute;
		bottom: 15px;
		left: 10px;
		cursor: pointer;
		color: rgba(0,0,0);
		transition: transform .2s;
}

input:focus + label,
input:not(:placeholder-shown) + label{transform: TransLateY(-24px);
		background: white;
		color: rgb(26,115,232);
		font-size: 14px;
		padding: 5px;
}

input:not(:focus) + label{color: rgba(0, 0, 0, .4);}
```
